version: '3.8'

services:
 web:
  build:
   context: .
  ports:
  - 8000:5000
  volumes: 
  - csv_data:/csv

 mysqldb:
  image: mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=password
  volumes:
  - mysql:/var/lib/mysql
  - mysql_config:/etc/mysql

volumes:
  mysql:
  mysql_config:
  csv_data: